version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes

  kafka:
    image: bitnami/kafka:3.4.0-debian-11-r0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_LOG_RETENTION_HOURS: 48
    depends_on:
      - zookeeper

  api:
    build: ./api-node
    depends_on:
      - kafka
    ports:
      - "3000:3000"
    environment:
      - KAFKA_BROKER=kafka:9092
    volumes:
      - ./api-node:/app
    working_dir: /app
    command: sh -c "echo 'Instalando dependências' && npm install && echo 'Dependências instaladas' && echo 'Iniciando API' && node index.js"


  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
      JVM_OPTS: -Xms32M -Xmx64M
    ports:
      - "9000:9000"
    depends_on:
      - kafka
  
  spark:
    image: jupyter/pyspark-notebook:latest
    ports:
      - "8888:8888"
    environment:
      - SPARK_MASTER=local[*]
      - PYSPARK_PYTHON=python3
    volumes:
      - ./notebooks:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''
    depends_on:
      - kafka
